{"variants":[{"paths":["\/documentation\/awsautoscalingplans\/internalserviceexception\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/AWSAutoScalingPlans\/documentation\/AWSAutoScalingPlans\/InternalServiceException\/Equatable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Operators","identifiers":["doc:\/\/AWSAutoScalingPlans\/documentation\/AWSAutoScalingPlans\/InternalServiceException\/!=(_:_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"AWSAutoScalingPlans"}],"role":"collectionGroup","title":"Equatable Implementations"},"hierarchy":{"paths":[["doc:\/\/AWSAutoScalingPlans\/documentation\/AWSAutoScalingPlans","doc:\/\/AWSAutoScalingPlans\/documentation\/AWSAutoScalingPlans\/InternalServiceException"]]},"references":{"doc://AWSAutoScalingPlans/documentation/AWSAutoScalingPlans/InternalServiceException":{"role":"symbol","title":"InternalServiceException","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InternalServiceException"}],"abstract":[{"type":"text","text":"The service encountered an internal error."}],"identifier":"doc:\/\/AWSAutoScalingPlans\/documentation\/AWSAutoScalingPlans\/InternalServiceException","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InternalServiceException"}],"url":"\/documentation\/awsautoscalingplans\/internalserviceexception"},"doc://AWSAutoScalingPlans/documentation/AWSAutoScalingPlans":{"role":"collection","title":"AWSAutoScalingPlans","abstract":[],"identifier":"doc:\/\/AWSAutoScalingPlans\/documentation\/AWSAutoScalingPlans","kind":"symbol","type":"topic","url":"\/documentation\/awsautoscalingplans"},"doc://AWSAutoScalingPlans/documentation/AWSAutoScalingPlans/InternalServiceException/!=(_:_:)":{"role":"symbol","title":"!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/AWSAutoScalingPlans\/documentation\/AWSAutoScalingPlans\/InternalServiceException\/!=(_:_:)","kind":"symbol","type":"topic","url":"\/documentation\/awsautoscalingplans\/internalserviceexception\/!=(_:_:)"}}}