{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/awsautoscalingplans\/internalserviceexception\/init(message:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/AWSAutoScalingPlans\/documentation\/AWSAutoScalingPlans\/InternalServiceException\/init(message:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"title":"init(message:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:19AWSAutoScalingPlans24InternalServiceExceptionV7messageACSSSg_tcfc","modules":[{"name":"AWSAutoScalingPlans"}]},"hierarchy":{"paths":[["doc:\/\/AWSAutoScalingPlans\/documentation\/AWSAutoScalingPlans","doc:\/\/AWSAutoScalingPlans\/documentation\/AWSAutoScalingPlans\/InternalServiceException"]]},"references":{"doc://AWSAutoScalingPlans/documentation/AWSAutoScalingPlans":{"role":"collection","title":"AWSAutoScalingPlans","abstract":[],"identifier":"doc:\/\/AWSAutoScalingPlans\/documentation\/AWSAutoScalingPlans","kind":"symbol","type":"topic","url":"\/documentation\/awsautoscalingplans"},"doc://AWSAutoScalingPlans/documentation/AWSAutoScalingPlans/InternalServiceException/init(message:)":{"role":"symbol","title":"init(message:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/AWSAutoScalingPlans\/documentation\/AWSAutoScalingPlans\/InternalServiceException\/init(message:)","kind":"symbol","type":"topic","url":"\/documentation\/awsautoscalingplans\/internalserviceexception\/init(message:)"},"doc://AWSAutoScalingPlans/documentation/AWSAutoScalingPlans/InternalServiceException":{"role":"symbol","title":"InternalServiceException","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InternalServiceException"}],"abstract":[{"type":"text","text":"The service encountered an internal error."}],"identifier":"doc:\/\/AWSAutoScalingPlans\/documentation\/AWSAutoScalingPlans\/InternalServiceException","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InternalServiceException"}],"url":"\/documentation\/awsautoscalingplans\/internalserviceexception"}}}