{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/AWSAuditManager\/documentation\/AWSAuditManager\/AuditManagerClientTypes","preciseIdentifier":"s:15AWSAuditManager05AuditB11ClientTypesO","text":"AuditManagerClientTypes"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/AWSAuditManager\/documentation\/AWSAuditManager\/AuditManagerClientTypes\/ValidationExceptionField","preciseIdentifier":"s:15AWSAuditManager05AuditB11ClientTypesO24ValidationExceptionFieldV","text":"ValidationExceptionField"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/awsauditmanager\/validationexception\/fields"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/AWSAuditManager\/documentation\/AWSAuditManager\/ValidationException\/fields","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The fields that caused the error, if applicable."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AuditManagerClientTypes","preciseIdentifier":"s:15AWSAuditManager05AuditB11ClientTypesO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ValidationExceptionField","preciseIdentifier":"s:15AWSAuditManager05AuditB11ClientTypesO24ValidationExceptionFieldV"},{"kind":"text","text":"]?"}],"title":"fields","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:15AWSAuditManager19ValidationExceptionV6fieldsSayAA05AuditB11ClientTypesO0cD5FieldVGSgvp","modules":[{"name":"AWSAuditManager"}]},"hierarchy":{"paths":[["doc:\/\/AWSAuditManager\/documentation\/AWSAuditManager","doc:\/\/AWSAuditManager\/documentation\/AWSAuditManager\/ValidationException"]]},"references":{"doc://AWSAuditManager/documentation/AWSAuditManager/ValidationException":{"role":"symbol","title":"ValidationException","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationException"}],"abstract":[{"type":"text","text":"The request has invalid or missing parameters."}],"identifier":"doc:\/\/AWSAuditManager\/documentation\/AWSAuditManager\/ValidationException","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ValidationException"}],"url":"\/documentation\/awsauditmanager\/validationexception"},"doc://AWSAuditManager/documentation/AWSAuditManager/ValidationException/fields":{"role":"symbol","title":"fields","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fields"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AuditManagerClientTypes","preciseIdentifier":"s:15AWSAuditManager05AuditB11ClientTypesO"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ValidationExceptionField","preciseIdentifier":"s:15AWSAuditManager05AuditB11ClientTypesO24ValidationExceptionFieldV"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The fields that caused the error, if applicable."}],"identifier":"doc:\/\/AWSAuditManager\/documentation\/AWSAuditManager\/ValidationException\/fields","kind":"symbol","type":"topic","url":"\/documentation\/awsauditmanager\/validationexception\/fields"},"doc://AWSAuditManager/documentation/AWSAuditManager/AuditManagerClientTypes/ValidationExceptionField":{"role":"symbol","title":"AuditManagerClientTypes.ValidationExceptionField","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationExceptionField"}],"abstract":[{"type":"text","text":"Indicates that the request has invalid or missing parameters for the field."}],"identifier":"doc:\/\/AWSAuditManager\/documentation\/AWSAuditManager\/AuditManagerClientTypes\/ValidationExceptionField","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ValidationExceptionField"}],"url":"\/documentation\/awsauditmanager\/auditmanagerclienttypes\/validationexceptionfield"},"doc://AWSAuditManager/documentation/AWSAuditManager":{"role":"collection","title":"AWSAuditManager","abstract":[],"identifier":"doc:\/\/AWSAuditManager\/documentation\/AWSAuditManager","kind":"symbol","type":"topic","url":"\/documentation\/awsauditmanager"},"doc://AWSAuditManager/documentation/AWSAuditManager/AuditManagerClientTypes":{"role":"symbol","title":"AuditManagerClientTypes","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuditManagerClientTypes"}],"abstract":[],"identifier":"doc:\/\/AWSAuditManager\/documentation\/AWSAuditManager\/AuditManagerClientTypes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuditManagerClientTypes"}],"url":"\/documentation\/awsauditmanager\/auditmanagerclienttypes"}}}