{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalServerException"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AWSAppConfig\/documentation\/AWSAppConfig\/InternalServerException","preciseIdentifier":"s:12AWSAppConfig23InternalServerExceptionV","text":"InternalServerException"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/awsappconfig\/deleteenvironmentoutputerror\/internalserverexception(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/AWSAppConfig\/documentation\/AWSAppConfig\/DeleteEnvironmentOutputError\/internalServerException(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalServerException"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"InternalServerException","preciseIdentifier":"s:12AWSAppConfig23InternalServerExceptionV"},{"kind":"text","text":")"}],"title":"DeleteEnvironmentOutputError.internalServerException(_:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:12AWSAppConfig28DeleteEnvironmentOutputErrorO23internalServerExceptionyAcA08InternalhI0VcACmF","modules":[{"name":"AWSAppConfig"}]},"hierarchy":{"paths":[["doc:\/\/AWSAppConfig\/documentation\/AWSAppConfig","doc:\/\/AWSAppConfig\/documentation\/AWSAppConfig\/DeleteEnvironmentOutputError"]]},"references":{"doc://AWSAppConfig/documentation/AWSAppConfig/DeleteEnvironmentOutputError/internalServerException(_:)":{"role":"symbol","title":"DeleteEnvironmentOutputError.internalServerException(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalServerException"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"InternalServerException","preciseIdentifier":"s:12AWSAppConfig23InternalServerExceptionV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AWSAppConfig\/documentation\/AWSAppConfig\/DeleteEnvironmentOutputError\/internalServerException(_:)","kind":"symbol","type":"topic","url":"\/documentation\/awsappconfig\/deleteenvironmentoutputerror\/internalserverexception(_:)"},"doc://AWSAppConfig/documentation/AWSAppConfig":{"role":"collection","title":"AWSAppConfig","abstract":[],"identifier":"doc:\/\/AWSAppConfig\/documentation\/AWSAppConfig","kind":"symbol","type":"topic","url":"\/documentation\/awsappconfig"},"doc://AWSAppConfig/documentation/AWSAppConfig/InternalServerException":{"role":"symbol","title":"InternalServerException","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InternalServerException"}],"abstract":[{"type":"text","text":"There was an internal failure in the AppConfig service."}],"identifier":"doc:\/\/AWSAppConfig\/documentation\/AWSAppConfig\/InternalServerException","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InternalServerException"}],"url":"\/documentation\/awsappconfig\/internalserverexception"},"doc://AWSAppConfig/documentation/AWSAppConfig/DeleteEnvironmentOutputError":{"role":"symbol","title":"DeleteEnvironmentOutputError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeleteEnvironmentOutputError"}],"abstract":[],"identifier":"doc:\/\/AWSAppConfig\/documentation\/AWSAppConfig\/DeleteEnvironmentOutputError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DeleteEnvironmentOutputError"}],"url":"\/documentation\/awsappconfig\/deleteenvironmentoutputerror"}}}