{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnknownAWSHttpServiceError","preciseIdentifier":"s:16AWSClientRuntime26UnknownAWSHttpServiceErrorV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/awsapprunner\/resumeserviceoutputerror\/unknown(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/AWSAppRunner\/documentation\/AWSAppRunner\/ResumeServiceOutputError\/unknown(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnknownAWSHttpServiceError","preciseIdentifier":"s:16AWSClientRuntime26UnknownAWSHttpServiceErrorV"},{"kind":"text","text":")"}],"title":"ResumeServiceOutputError.unknown(_:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:12AWSAppRunner24ResumeServiceOutputErrorO7unknownyAC16AWSClientRuntime014UnknownAWSHttpdF0VcACmF","modules":[{"name":"AWSAppRunner"}]},"hierarchy":{"paths":[["doc:\/\/AWSAppRunner\/documentation\/AWSAppRunner","doc:\/\/AWSAppRunner\/documentation\/AWSAppRunner\/ResumeServiceOutputError"]]},"references":{"doc://AWSAppRunner/documentation/AWSAppRunner/ResumeServiceOutputError":{"role":"symbol","title":"ResumeServiceOutputError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResumeServiceOutputError"}],"abstract":[],"identifier":"doc:\/\/AWSAppRunner\/documentation\/AWSAppRunner\/ResumeServiceOutputError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ResumeServiceOutputError"}],"url":"\/documentation\/awsapprunner\/resumeserviceoutputerror"},"doc://AWSAppRunner/documentation/AWSAppRunner/ResumeServiceOutputError/unknown(_:)":{"role":"symbol","title":"ResumeServiceOutputError.unknown(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnknownAWSHttpServiceError","preciseIdentifier":"s:16AWSClientRuntime26UnknownAWSHttpServiceErrorV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AWSAppRunner\/documentation\/AWSAppRunner\/ResumeServiceOutputError\/unknown(_:)","kind":"symbol","type":"topic","url":"\/documentation\/awsapprunner\/resumeserviceoutputerror\/unknown(_:)"},"doc://AWSAppRunner/documentation/AWSAppRunner":{"role":"collection","title":"AWSAppRunner","abstract":[],"identifier":"doc:\/\/AWSAppRunner\/documentation\/AWSAppRunner","kind":"symbol","type":"topic","url":"\/documentation\/awsapprunner"}}}