{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnknownAWSHttpServiceError","preciseIdentifier":"s:16AWSClientRuntime26UnknownAWSHttpServiceErrorV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/awsappsync\/updatedatasourceoutputerror\/unknown(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/AWSAppSync\/documentation\/AWSAppSync\/UpdateDataSourceOutputError\/unknown(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnknownAWSHttpServiceError","preciseIdentifier":"s:16AWSClientRuntime26UnknownAWSHttpServiceErrorV"},{"kind":"text","text":")"}],"title":"UpdateDataSourceOutputError.unknown(_:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:10AWSAppSync27UpdateDataSourceOutputErrorO7unknownyAC16AWSClientRuntime021UnknownAWSHttpServiceG0VcACmF","modules":[{"name":"AWSAppSync"}]},"hierarchy":{"paths":[["doc:\/\/AWSAppSync\/documentation\/AWSAppSync","doc:\/\/AWSAppSync\/documentation\/AWSAppSync\/UpdateDataSourceOutputError"]]},"references":{"doc://AWSAppSync/documentation/AWSAppSync":{"role":"collection","title":"AWSAppSync","abstract":[],"identifier":"doc:\/\/AWSAppSync\/documentation\/AWSAppSync","kind":"symbol","type":"topic","url":"\/documentation\/awsappsync"},"doc://AWSAppSync/documentation/AWSAppSync/UpdateDataSourceOutputError/unknown(_:)":{"role":"symbol","title":"UpdateDataSourceOutputError.unknown(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnknownAWSHttpServiceError","preciseIdentifier":"s:16AWSClientRuntime26UnknownAWSHttpServiceErrorV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AWSAppSync\/documentation\/AWSAppSync\/UpdateDataSourceOutputError\/unknown(_:)","kind":"symbol","type":"topic","url":"\/documentation\/awsappsync\/updatedatasourceoutputerror\/unknown(_:)"},"doc://AWSAppSync/documentation/AWSAppSync/UpdateDataSourceOutputError":{"role":"symbol","title":"UpdateDataSourceOutputError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UpdateDataSourceOutputError"}],"abstract":[],"identifier":"doc:\/\/AWSAppSync\/documentation\/AWSAppSync\/UpdateDataSourceOutputError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UpdateDataSourceOutputError"}],"url":"\/documentation\/awsappsync\/updatedatasourceoutputerror"}}}