{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalServiceError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/AWSAppIntegrations\/documentation\/AWSAppIntegrations\/InternalServiceError","preciseIdentifier":"s:18AWSAppIntegrations20InternalServiceErrorV","text":"InternalServiceError"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/awsappintegrations\/untagresourceoutputerror\/internalserviceerror(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/AWSAppIntegrations\/documentation\/AWSAppIntegrations\/UntagResourceOutputError\/internalServiceError(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalServiceError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"InternalServiceError","preciseIdentifier":"s:18AWSAppIntegrations20InternalServiceErrorV"},{"kind":"text","text":")"}],"title":"UntagResourceOutputError.internalServiceError(_:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:18AWSAppIntegrations24UntagResourceOutputErrorO015internalServiceF0yAcA08InternalhF0VcACmF","modules":[{"name":"AWSAppIntegrations"}]},"hierarchy":{"paths":[["doc:\/\/AWSAppIntegrations\/documentation\/AWSAppIntegrations","doc:\/\/AWSAppIntegrations\/documentation\/AWSAppIntegrations\/UntagResourceOutputError"]]},"references":{"doc://AWSAppIntegrations/documentation/AWSAppIntegrations":{"role":"collection","title":"AWSAppIntegrations","abstract":[],"identifier":"doc:\/\/AWSAppIntegrations\/documentation\/AWSAppIntegrations","kind":"symbol","type":"topic","url":"\/documentation\/awsappintegrations"},"doc://AWSAppIntegrations/documentation/AWSAppIntegrations/UntagResourceOutputError/internalServiceError(_:)":{"role":"symbol","title":"UntagResourceOutputError.internalServiceError(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalServiceError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"InternalServiceError","preciseIdentifier":"s:18AWSAppIntegrations20InternalServiceErrorV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AWSAppIntegrations\/documentation\/AWSAppIntegrations\/UntagResourceOutputError\/internalServiceError(_:)","kind":"symbol","type":"topic","url":"\/documentation\/awsappintegrations\/untagresourceoutputerror\/internalserviceerror(_:)"},"doc://AWSAppIntegrations/documentation/AWSAppIntegrations/InternalServiceError":{"role":"symbol","title":"InternalServiceError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InternalServiceError"}],"abstract":[{"type":"text","text":"Request processing failed due to an error or failure with the service."}],"identifier":"doc:\/\/AWSAppIntegrations\/documentation\/AWSAppIntegrations\/InternalServiceError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InternalServiceError"}],"url":"\/documentation\/awsappintegrations\/internalserviceerror"},"doc://AWSAppIntegrations/documentation/AWSAppIntegrations/UntagResourceOutputError":{"role":"symbol","title":"UntagResourceOutputError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UntagResourceOutputError"}],"abstract":[],"identifier":"doc:\/\/AWSAppIntegrations\/documentation\/AWSAppIntegrations\/UntagResourceOutputError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UntagResourceOutputError"}],"url":"\/documentation\/awsappintegrations\/untagresourceoutputerror"}}}