{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/awsappsync\/unauthorizedexception\/message"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/AWSAppSync\/documentation\/AWSAppSync\/UnauthorizedException\/message","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"message","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:10AWSAppSync21UnauthorizedExceptionV7messageSSSgvp","modules":[{"name":"AWSAppSync"}]},"hierarchy":{"paths":[["doc:\/\/AWSAppSync\/documentation\/AWSAppSync","doc:\/\/AWSAppSync\/documentation\/AWSAppSync\/UnauthorizedException"]]},"references":{"doc://AWSAppSync/documentation/AWSAppSync":{"role":"collection","title":"AWSAppSync","abstract":[],"identifier":"doc:\/\/AWSAppSync\/documentation\/AWSAppSync","kind":"symbol","type":"topic","url":"\/documentation\/awsappsync"},"doc://AWSAppSync/documentation/AWSAppSync/UnauthorizedException":{"role":"symbol","title":"UnauthorizedException","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"UnauthorizedException"}],"abstract":[{"type":"text","text":"You arenâ€™t authorized to perform this operation."}],"identifier":"doc:\/\/AWSAppSync\/documentation\/AWSAppSync\/UnauthorizedException","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UnauthorizedException"}],"url":"\/documentation\/awsappsync\/unauthorizedexception"},"doc://AWSAppSync/documentation/AWSAppSync/UnauthorizedException/message":{"role":"symbol","title":"message","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AWSAppSync\/documentation\/AWSAppSync\/UnauthorizedException\/message","kind":"symbol","type":"topic","url":"\/documentation\/awsappsync\/unauthorizedexception\/message"}}}